### ISSUE TITLE
Add a Vercel Button

### ISSUE THREAD

**Issue by 3kh0** [BinBashBanana/deploy-buttons#1]
Can you add a deploy button for Vercel?

Here is the official one:
> [![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new/clone?repository-url=https%3A%2F%2Fgithub.com%2F3kh0%2F3kh0.github.io) 

Please make it so the button background is black because blue does not fit with the theme

**Comment by BinBashBanana** [comment]
Done
