### ISSUE TITLE
Add a Netify Button

### ISSUE THREAD

**Issue by 3kh0** [BinBashBanana/deploy-buttons#2]
Can you make a button for netify?

Here is the official one:
> [![Deploy with Netlify](https://www.netlify.com/img/deploy/button.svg)](https://app.netlify.com/start/deploy?repository=https://github.com/3kh0/3kh0.github.io)

**Comment by 3kh0** [comment]
@BinBashBanana will this ever be done?

**Comment by BinBashBanana** [comment]
I completely forgot about this, sorry. Are there any others besides vercel and netlify that you can think of?

**Comment by 3kh0** [comment]
> I completely forgot about this, sorry. Are there any others besides vercel and netlify that you can think of?

not really, thanks for your time!

**Comment by BinBashBanana** [comment]
Done
