### ISSUE TITLE
Add button for render

### ISSUE THREAD

**Issue by 3kh0** [BinBashBanana/deploy-buttons#5]
Link to the website: https://render.com/

**Comment by BinBashBanana** [comment]
I won't be making buttons for static-only hosts.

**Comment by 3kh0** [comment]
@BinBashBanana it also does docker containers and more
![image](https://user-images.githubusercontent.com/58097612/193712115-d2ef1b6f-13e1-4cc7-9371-4da716b705c0.png)
![image](https://user-images.githubusercontent.com/58097612/193712317-79a85abb-2cb1-46b9-a07f-bbf715d36735.png)

**Comment by 3kh0** [comment]
https://community.render.com/t/deploy-with-github-url/6140

I made a post on the community to find the url (if there is one)

**Comment by BinBashBanana** [comment]
Looks like it's possible after all, I'll make one (it requires a configuration file like heroku)

**Comment by 3kh0** [comment]
Completed with c7c77ff
